<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13151" started-at="2018-03-07T04:14:06Z" finished-at="2018-03-07T04:14:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13151" started-at="2018-03-07T04:14:06Z" finished-at="2018-03-07T04:14:19Z">
      <class name="com.amazonaws.tests.AWSCalculatorTests">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.amazonaws.tests.AWSCalculatorTests@1da2cb77]" name="setUp" is-config="true" duration-ms="5258" started-at="2018-03-06T23:14:06Z" finished-at="2018-03-06T23:14:11Z">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="deafultMonthlyBillTest()[pri:0, instance:com.amazonaws.tests.AWSCalculatorTests@1da2cb77]" name="deafultMonthlyBillTest" duration-ms="2009" started-at="2018-03-06T23:14:11Z" description="Monthly bill should be $0.00 by default" finished-at="2018-03-06T23:14:13Z">
          <exception class="java.lang.ArrayIndexOutOfBoundsException">
            <message>
              <![CDATA[1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1at com.amazonaws.pages.AwsCalculatorPage.getMonthlyBillAmount(AwsCalculatorPage.java:44)at com.amazonaws.tests.AWSCalculatorTests.deafultMonthlyBillTest(AWSCalculatorTests.java:19)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArrayIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deafultMonthlyBillTest -->
        <test-method status="PASS" signature="addedEc2DefaultValuesTest()[pri:1, instance:com.amazonaws.tests.AWSCalculatorTests@1da2cb77]" name="addedEc2DefaultValuesTest" duration-ms="5864" started-at="2018-03-06T23:14:13Z" finished-at="2018-03-06T23:14:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addedEc2DefaultValuesTest -->
      </class> <!-- com.amazonaws.tests.AWSCalculatorTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
